### ISSUE TITLE
add package config normalizer

### ISSUE THREAD

**Issue by kamilsk** [octolab/Cleaner#13]
normalize

``` yaml
extra:
  dev-files:
  - "/docs/*"
  - "!docs/LICENSE.md"
```

to

``` yaml
extra:
  dev-files:
    other: ["/docs/*", "!docs/LICENSE.md"]
```
