### ISSUE TITLE
add the ability to remove any files in target package(s)

### ISSUE THREAD

**Issue by kamilsk** [octolab/Cleaner#37]
``` yaml
config:
  octolab/cleaner:
    clean: ...
    force:
      vendor/package1: [file1, file2, etc]
```
